# -*- coding: utf-8 -*-
"""KırmızıSarapKalitesiAnalizi.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ewD6KdiqUomolOREToY1TTLtzeeZ4AqD
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")

dfC = pd.read_csv("winequality-red.csv")

df = dfC.copy()

df.head(3)

df.tail(3)

df.shape

df.info()

df.describe().T

df.isnull().sum()

df.median()

plt.figure(figsize= (17,5))
plt.subplot(1,3,1)
sns.barplot(x= "quality", y= "fixed acidity", data = df, color = 'red')

plt.subplot(1,3,2)
sns.barplot(x= "quality", y = "volatile acidity", data = df, color = 'green')

plt.subplot(1,3,3)
sns.barplot(x= "quality", y= "citric acid", data = df)

plt.show()

sns.pairplot(df, hue='quality', diag_kind='hist', height=1, aspect=1.5)
plt.show()

plt.figure(figsize = (17,6))
plt.subplot(1,3,1)
sns.kdeplot(df.quality, shade = True, color = 'red')

plt.subplot(1,3,2)
sns.kdeplot(df.alcohol, shade = True, color = 'green')

plt.subplot(1,3,3)
sns.kdeplot(df.pH, shade = True, color = 'blue')

plt.show()

plt.figure(figsize= (17,6))
plt.subplot(1,3,1)
sns.boxplot(x= "quality", y= "alcohol", data =df, color = 'yellow')

plt.subplot(1,3,2)
sns.boxplot(x= "quality", y= "pH", data = df, color = 'pink')

plt.subplot(1,3,3)
sns.boxplot(x= "quality", y= "density", data = df, color = 'blue')

plt.show()

plt.figure(figsize= (17,6))
sns.catplot(x= "quality", y= "alcohol", data =df, kind = "violin", color= 'red')

plt.figure(figsize= (17,6))
sns.catplot(x= "quality", y= "pH", data= df, kind= "violin")

corr = df.corr()

print(corr)

plt.figure(figsize= (17,8))
sns.heatmap(corr, annot = True, cmap = "coolwarm", fmt=".2f", linewidths=0.6, linecolor="gray")
plt.show()

plt.figure(figsize= (17,6))
sns.scatterplot(x= "quality", y= "residual sugar", data= df)
plt.show()



